name: Development Desktop Build

on:
  push:
    branches: [ master ]

jobs:
  pre-release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Remove :android project
        run: |
          mv android/assets .
          rm -rf android
          mkdir android
          mv assets android
          cat build.gradle | awk -F"\"" 'BEGIN { cnt=0 } { ok="+"; if ($2 == ":android" || cnt != 0) { for(i=1; i<=length($0); i++) { if (substr($0, i, 1) == "{") { cnt++; } else if (substr($0, i, 1) == "}") { cnt--; ok="-"; } } } if (cnt == 0 && ok != "-") { print $0; } }' > .build.gradle
          mv .build.gradle build.gradle

      # BEGIN {
      #         cnt=0
      # }
      # {
      #         ok="+";
      #         if ($2 == ":android" || cnt != 0) {
      #                 for(i=1; i<=length($0); i++) {
      #                         if (substr($0, i, 1) == "{") {
      #                                 cnt++;
      #                         } else if (substr($0, i, 1) == "}") {
      #                                 cnt--;
      #                                 ok="-";
      #                         }
      #                 }
      #         }
      #         if (cnt == 0 && ok != "-") {
      #                 print $0;
      #         }
      # }

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build and generate .jar with Gradle
        run: ./gradlew :desktop:dist
      - name: Rename generated .jar
        run: |
          cd desktop/build/libs
          JAR_NAME=$(ls | grep .jar | head -n1)
          cd ../../../
          mv "desktop/build/libs/$JAR_NAME" .
          mv "$JAR_NAME" todd.jar

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v1-alpha"
          prerelease: true
          title: "Development Desktop Build"
          files: todd.jar
