name: Json Docs Deployment
on:
  push:
    branches:
    - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Remove :android project
        run: |
          mv android/assets .
          rm -rf android
          mkdir android
          mv assets android
          cat build.gradle | awk -F"\"" 'BEGIN { cnt=0 } { ok="+"; if ($2 == ":android" || cnt != 0) { for(i=1; i<=length($0); i++) { if (substr($0, i, 1) == "{") { cnt++; } else if (substr($0, i, 1) == "}") { cnt--; ok="-"; } } } if (cnt == 0 && ok != "-") { print $0; } }' > .build.gradle
          mv .build.gradle build.gradle

      # BEGIN {
      #         cnt=0
      # }
      # {
      #         ok="+";
      #         if ($2 == ":android" || cnt != 0) {
      #                 for(i=1; i<=length($0); i++) {
      #                         if (substr($0, i, 1) == "{") {
      #                                 cnt++;
      #                         } else if (substr($0, i, 1) == "}") {
      #                                 cnt--;
      #                                 ok="-";
      #                         }
      #                 }
      #         }
      #         if (cnt == 0 && ok != "-") {
      #                 print $0;
      #         }
      # }

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Publish JSON docs dokka plugin to local maven repository
        run: ./gradlew :plugins:docs:publishToMavenLocal
        
      - name: Generate JSON docs
        run: ./gradlew :core:dokkaHtml

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: core/build/dokka/html
          git-config-name: Kazakov Mihail
